### ISSUE TITLE
Delete entries from table and repopulate table from API at the same time

### ISSUE THREAD

**Issue by codemanimal** [codemanimal/Stream_Guide#6]
On each page load, I would like to delete all the entries (videos) in my database table and then make a call to the dailymotion API in order to repopulate that table with refreshed data. I believe that I am having a synchronization error because the videos table is not being repopulated. 

I'm trying to do something like...

```
	$.ajax({
		url: '/videos_delete',
	 	method: 'DELETE'	
	}).then(function() {
		$.get('/videos_search');
	});
```

I am doing this because I am bulkCreating when I 'GET videos_search', but I get a validation error because of unique validations (I dont want the same video saved to my database twice). Thus, I want to clear the table each time before I call the get request.

**Comment by codemanimal** [comment]
@bigtone1284 @h4w5 @WilliamfShaw @harimohanraj89 @DrRobotmck

**Comment by DrRobotmck** [comment]
Which branch are you working on @codemanimal?

**Comment by codemanimal** [comment]
just merged to development @DrRobotmck

**Comment by DrRobotmck** [comment]
@codemanimal Can you add in the specific error messages that you are getting back?

Also,
Where do you define `status`?
```js
// Delete all videos from videos table
app.delete('/videos_delete', function(req, res) {
  Video.destroy({ truncate: true })
    .then(function(videos) {
      res.sendStatus(status);
    });
});
```

**Comment by codemanimal** [comment]
@DrRobotmck I just changed 'status' to 'videos'.

error message in terminal: 
```
Possibly unhandled SequelizeUniqueConstraintError: Validation error
    at module.exports.Query.formatError (/Users/braintrust/Dev/Stream_Guide/node_modules/sequelize/lib/dialects/postgres/query.js:390:18)
    at null.<anonymous> (/Users/braintrust/Dev/Stream_Guide/node_modules/sequelize/lib/dialects/postgres/query.js:106:21)
    at emit (events.js:107:17)
    at Query.handleError (/Users/braintrust/Dev/Stream_Guide/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/Users/braintrust/Dev/Stream_Guide/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/braintrust/Dev/Stream_Guide/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

**Comment by codemanimal** [comment]
@DrRobotmck I have a 'unique' validation on the dailymotion video id so that I do not save the same video twice. I could try findOrCreate, but I need to bulkCreate, so I thought the solution was to clear the table using a delete request before I call the DM api and bulkCreate the response into my table.
